version: '2'

services:
  scala:
    build: .
    environment:
      JVM_OPTS: >
        -Dhttp.proxyHost=127.0.0.1 
        -Dhttp.proxyPort=2080
    volumes:
      - .:/meeting_reminder
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt