version: '2'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  scala:
    build: .
    environment:
      JVM_OPTS: >
        -Dhttp.proxyHost=127.0.0.1 
        -Dhttp.proxyPort=2080
        -Dhttps.proxyHost=127.0.0.1 
        -Dhttps.proxyPort=2080
      DB_NAME: "postgres"
      DB_PASS: "1234"
      DB_URL: "localhost"
      DB_USER: "postgres"
      BOT_TOKEN: "6957676242:AAEIVOZLa7GsTyRSAKeCVUhAUQHQvBXhGew"
    volumes:
      - .:/meeting_reminder
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt
    depends_on: [db]